<a href="https://colab.research.google.com/github/Deepthi25B/E-Commerce_Customer_Churn_Analysis/blob/main/MAIN_DA_FINAL_PROJECT_Customer_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Title

Customer Sentiment Analysis on India’s Fast Delivery Services like Blinkit, Swiggy Instamart and Jio Mart by Using Python

# Domain

Sales and E-commerce

# Objective

1. To clean, transform, and preprocess the dataset to ensure data quality and consistency for analysis

2. To explore patterns and trends in customer ratings and feedback through exploratory data analysis (EDA).

3. To study customer feedback and rating patterns of fast delivery platforms in India.

4. To identify customer sentiment (positive, negative, or neutral) from review texts using sentiment analysis and determine the key factors affecting customer experience in fast delivery services.

5. To visualize customer opinions using Python tools such as Pandas, Matplotlib, and Seaborn to clearly explain the data, and to provide actionable insights and recommendations to improve delivery service quality and customer experience.

# Outcome

The project helps uncover key patterns, trends, and hidden insights from customer reviews and ratings of fast delivery services. The analysis provides a clear understanding of customer sentiments and satisfaction levels using Python-based visualization tools. It also supports better decision-making by offering data-driven insights to improve delivery service quality and customer experience.

#Dataset Information

Source: Kaggle

Dataset Description:

Agent Name: Represents the fast delivery platform or service provider.

Rating: Indicates the overall customer rating given to the delivery service.

Review Text: Contains the written feedback or comments provided by customers about their delivery experience.

Delivery Time (min): Shows the time taken for the order to be delivered, measured in minutes.

Location: Represents the city or area where the delivery service was provided.

Order Type: Indicates the type of order placed by the customer.

Customer Feedback Type: Classifies the type of feedback given by the customer, such as positive, negative, or neutral.

Price Range: Shows the price category of the ordered items.

Discount Applied: Indicates whether any discount was applied to the order.

Product Availability: Shows whether the ordered product was available or not at the time of purchase.

Customer Service Rating: Represents the rating given by customers for the customer service provided.

Order Accuracy: Indicates whether the delivered order was correct or incorrect.

# Type of Analysis

Exploratory Data Analysis (EDA):Exploring patterns and trends in customer ratings and feedback using summary statistics and visualizations.

Descriptive and Diagnostic Analysis:Summarizing the dataset and identifying key factors that influence customer satisfaction in fast delivery services.

Prescriptive Analysis:Providing data-driven insights and recommendations to improve delivery service quality and customer experience.

# Stages for DA Project

## Stage 1 – Problem Definition and Dataset Selection

Define the business problem and expected outcome

Choose dataset and explain its source, size, and features

Import libraries, load dataset

Dataset description (rows, columns, features)

Initial EDA (head, info, describe, shape, null checks, duplicate check)

In [14]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
from google.colab import files
uploaded = files.upload()

Saving RAW DATASET Fast Delivery Agent Reviews.csv to RAW DATASET Fast Delivery Agent Reviews (1).csv

In [16]:
df = pd.read_csv("RAW DATASET Fast Delivery Agent Reviews (1).csv")

In [17]:
import pandas as pd
df = pd.read_csv("RAW DATASET Fast Delivery Agent Reviews (1).csv")

In [18]:
df.head()

,Agent Name,Rating,Review Text,Delivery Time (min),Location,Order Type,Customer Feedback Type,Price Range,Discount Applied,Product Availability,Customer Service Rating,Order Accuracy
0,Zepto,4.5,Purpose boy job cup decision girl now get job ...,58,Delhi,Essentials,Neutral,High,Yes,Out of Stock,4,Incorrect
1,Zepto,2.1,Prevent production able both the box school wa...,25,Lucknow,Grocery,Negative,Low,No,Out of Stock,2,Correct
2,JioMart,4.5,Family station listen agreement more kitchen l...,54,Ahmedabad,Essentials,Neutral,Low,No,Out of Stock,3,Correct
3,JioMart,2.6,World north people area everything enter beyon...,22,Chennai,Essentials,Neutral,Low,Yes,In Stock,1,Incorrect
4,Zepto,3.6,Hand way yourself tax whether sister anyone ef...,34,Pune,Pharmacy,Positive,High,No,In Stock,2,Incorrect

In [19]:
print(df.shape)

(5000, 12)

In [20]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Agent Name               5000 non-null   object
 1   Rating                   5000 non-null   float64
 2   Review Text              5000 non-null   object
 3   Delivery Time (min)      5000 non-null   int64
 4   Location                 5000 non-null   object
 5   Order Type               5000 non-null   object
 6   Customer Feedback Type   5000 non-null   object
 7   Price Range              5000 non-null   object
 8   Discount Applied         5000 non-null   object
 9   Product Availability     5000 non-null   object
 10  Customer Service Rating  5000 non-null   int64
 11  Order Accuracy           5000 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 468.9+ KB
None

In [21]:
print(df.describe())

           Rating  Delivery Time (min)  Customer Service Rating
count  5000.00000          5000.000000              5000.000000
mean      3.00290            34.962400                 2.972000
std       1.15214            14.789656                 1.409969
min       1.00000            10.000000                 1.000000
25%       2.00000            22.000000                 2.000000
50%       3.00000            35.000000                 3.000000
75%       4.00000            48.000000                 4.000000
max       5.00000            60.000000                 5.000000

In [22]:
print(df.columns)

Index(['Agent Name', 'Rating', 'Review Text', 'Delivery Time (min)',
       'Location', 'Order Type', 'Customer Feedback Type', 'Price Range',
       'Discount Applied', 'Product Availability', 'Customer Service Rating',
       'Order Accuracy'],
      dtype='object')

In [23]:
print(df.dtypes)

Agent Name                  object
Rating                     float64
Review Text                 object
Delivery Time (min)          int64
Location                    object
Order Type                  object
Customer Feedback Type      object
Price Range                 object
Discount Applied            object
Product Availability        object
Customer Service Rating      int64
Order Accuracy              object
dtype: object

In [24]:
print(df.head())

  Agent Name  Rating                                        Review Text  \
0      Zepto     4.5  Purpose boy job cup decision girl now get job ...
1      Zepto     2.1  Prevent production able both the box school wa...
2    JioMart     4.5  Family station listen agreement more kitchen l...
3    JioMart     2.6  World north people area everything enter beyon...
4      Zepto     3.6  Hand way yourself tax whether sister anyone ef...

   Delivery Time (min)   Location  Order Type Customer Feedback Type  \
0                   58      Delhi  Essentials                Neutral
1                   25    Lucknow     Grocery               Negative
2                   54  Ahmedabad  Essentials                Neutral
3                   22    Chennai  Essentials                Neutral
4                   34       Pune    Pharmacy               Positive

  Price Range Discount Applied Product Availability  Customer Service Rating  \
0        High              Yes         Out of Stock                        4
1         Low               No         Out of Stock                        2
2         Low               No         Out of Stock                        3
3         Low              Yes             In Stock                        1
4        High               No             In Stock                        2

  Order Accuracy
0      Incorrect
1        Correct
2        Correct
3      Incorrect
4      Incorrect

In [25]:
print(df.isnull().sum())

Agent Name                 0
Rating                     0
Review Text                0
Delivery Time (min)        0
Location                   0
Order Type                 0
Customer Feedback Type     0
Price Range                0
Discount Applied           0
Product Availability       0
Customer Service Rating    0
Order Accuracy             0
dtype: int64

In [26]:
print(df.duplicated().sum())

0

## Stage 2 – Data Cleaning and Pre-processing

Handle missing values (impute or drop)

Handle duplicates

Treat outliers if required

Check skewness and apply transformations

Convert data types if needed

Feature transformations (date parts, derived fields if required for analysis)

In [27]:
# Clean column names
df.columns = df.columns.str.strip()

In [28]:
# Check missing values
df.isnull().sum()

Agent Name                 0
Rating                     0
Review Text                0
Delivery Time (min)        0
Location                   0
Order Type                 0
Customer Feedback Type     0
Price Range                0
Discount Applied           0
Product Availability       0
Customer Service Rating    0
Order Accuracy             0
dtype: int64

In [29]:
# Fill numerical columns with mean
num_cols = ['Rating', 'Delivery Time (min)', 'Customer Service Rating']
for col in num_cols:
    if col in df.columns:
        df[col].fillna(df[col].mean(), inplace=True)

/tmp/ipykernel_5375/2472620625.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [31]:
# Fill categorical columns with mode
cat_cols = ['Agent Name', 'Review Text', 'Location', 'Order Type',
            'Customer Feedback Type', 'Price Range',
            'Discount Applied', 'Product Availability', 'Order Accuracy']
for col in cat_cols:
    if col in df.columns:
        df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_5375/51710606.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [32]:
# Check duplicate rows
df.duplicated().sum()

np.int64(0)

In [33]:
# Remove duplicates
df.drop_duplicates(inplace=True)

In [34]:
import numpy as np

# Function to remove outliers using IQR
def remove_outliers(col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return df[(df[col] >= lower) & (df[col] <= upper)]

In [35]:
# Apply for important numerical columns
for col in ['Rating', 'Delivery Time (min)', 'Customer Service Rating']:
    if col in df.columns:
        df = remove_outliers(col)

In [36]:
# Check skewness
df[['Rating', 'Delivery Time (min)', 'Customer Service Rating']].skew()

Rating                    -0.003902
Delivery Time (min)        0.014605
Customer Service Rating    0.015343
dtype: float64

In [37]:
# Apply log transformation for skewed column
if 'Delivery Time (min)' in df.columns:
    df['Delivery Time (min)'] = np.log1p(df['Delivery Time (min)'])

In [38]:
# Convert categorical columns
for col in cat_cols:
    if col in df.columns:
        df[col] = df[col].astype('category')

In [39]:
# Ensure numeric columns are correct
for col in num_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [49]:
# Create Rating Category
df['Rating_Category'] = df['Rating'].apply(
    lambda x: 'High' if x >= 4 else 'Medium' if x >= 3 else 'Low'
)
# Create Delivery Speed Category
df['Delivery_Speed'] = df['Delivery Time (min)'].apply(
    lambda x: 'Fast' if x <= 30 else 'Moderate' if x <= 60 else 'Slow'
)
# Convert Discount Applied to binary
df['Discount Applied'] = df['Discount Applied'].map({'Yes': 1, 'No': 0})


# Convert Order Accuracy to binary
df['Order Accuracy'] = df['Order Accuracy'].map({'Correct': 1, 'Incorrect': 0})

In [50]:
display(df)

,Agent Name,Rating,Review Text,Delivery Time (min),Location,Order Type,Customer Feedback Type,Price Range,Discount Applied,Product Availability,Customer Service Rating,Order Accuracy,Rating_Category,Delivery_Speed
0,Zepto,4.5,Purpose boy job cup decision girl now get job ...,4.077537,Delhi,Essentials,Neutral,High,NaN,NaN,4,NaN,High,Fast
1,Zepto,2.1,Prevent production able both the box school wa...,3.258097,Lucknow,Grocery,Negative,Low,NaN,NaN,2,NaN,Low,Fast
2,JioMart,4.5,Family station listen agreement more kitchen l...,4.007333,Ahmedabad,Essentials,Neutral,Low,NaN,NaN,3,NaN,High,Fast
3,JioMart,2.6,World north people area everything enter beyon...,3.135494,Chennai,Essentials,Neutral,Low,NaN,NaN,1,NaN,Low,Fast
4,Zepto,3.6,Hand way yourself tax whether sister anyone ef...,3.555348,Pune,Pharmacy,Positive,High,NaN,NaN,2,NaN,Medium,Fast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Blinkit,2.4,Assume president far economic us discuss hand ...,4.043051,Bangalore,Grocery,Neutral,High,NaN,NaN,1,NaN,Low,Fast
4996,JioMart,3.2,Chance new edge beyond pass treat laugh woman ...,3.828641,Hyderabad,Grocery,Negative,Low,NaN,NaN,2,NaN,Medium,Fast
4997,Zepto,4.7,Until few population choose value behavior win...,3.891820,Pune,Pharmacy,Positive,High,NaN,NaN,5,NaN,High,Fast
4998,JioMart,3.8,Fight where recently half enter information ki...,2.484907,Bangalore,Food,Negative,High,NaN,NaN,1,NaN,Medium,Fast
4999,JioMart,4.5,Agreement challenge boy coach low person these...,2.772589,Pune,Grocery,Neutral,High,NaN,NaN,1,NaN,High,Fast

In [51]:
# Cleaned Dataset
df.to_csv("RAW DATASET Fast Delivery Agent Reviews (1).csv", index = False)

## Stage 3 – EDA and Visualizations

Univariate Analysis → distribution of single variables (countplot, histogram, boxplot)

Bivariate Analysis → relation between two variables (scatterplot, barplot, correlation heatmap)

Multivariate Analysis → relation among 3+ variables (pairplot, grouped analysis, pivot tables, advanced plots)

Interpretation MUST with every visualization

Focus on business story not just charts

Each chart must be in seperate cells.

In [ ]:
# your chart here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

## Stage 4 – Documentation, Insights and Presentation

Show a dashboard aligning all the charts in powerbi by connecting python in PowerBI

Summarize findings in plain English (what do the patterns mean)

Highlight 3–5 key insights (trends, anomalies, correlations)

Provide recommendations for business or decision-making

Explain the FINAL STORY WITH THE DASHBOARD

Create a PDF pasting your DASHBOARD, explaining all the above mentioned concepts and submit it

In [ ]:
# your stage 4 pdf Link

'''
step1 --> Create a docs that should have all the above mentioned
step2 --> Save it as "Stage4_doc"
Step3 --> Download it as PDF
step4 --> Upload the pdf in your drive
step5 --> Right click on your pdf in drive
step6 --> click share and change access into anyone with the link (Viewer)
step7 --> click copy link and paste it here...
You are done.
'''

# Future Enhancement

Use a larger or more recent dataset for deeper insights

Automate parts of the analysis with scripts or dashboards

Add advanced visualizations and interactive dashboards in Power BI or Tableau

Extend the analysis to predictive modeling for forecasting if needed

# Conclusion

From the analysis, we identified meaningful relationships and patterns in the dataset. The visualizations and insights highlight the main factors influencing the outcomes and provide a strong foundation for business decisions.